In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [3]:
attr = ['sequence_name','Mcg','Gvh','Lip','Chg','Aac','Alm1','Alm2','Site']
data = pd.read_csv('ecoli.txt',header=None,delim_whitespace=True,names=attr)
#data = data.drop('sequence_name',1)
data.head()

sequence_name   Mcg   Gvh   Lip  Chg   Aac  Alm1  Alm2 Site
0     AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35   cp
1    ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44   cp
2    ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46   cp
3    ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36   cp
4     ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35   cp

In [4]:
ecoli_site = data['Site']

In [5]:
tmp_ecoli=list(set(ecoli_site))
tmp_ecoli

['cp', 'imS', 'imL', 'omL', 'pp', 'imU', 'om', 'im']

In [6]:
features = [i for i in range(len(tmp_ecoli))]
features

[0, 1, 2, 3, 4, 5, 6, 7]

In [7]:
map_features = {v:k for k,v in zip(features,tmp_ecoli)}
map_features

{'cp': 0, 'im': 7, 'imL': 2, 'imS': 1, 'imU': 5, 'om': 6, 'omL': 3, 'pp': 4}

In [8]:
tmp2_ecoli=list(ecoli_site)

In [9]:
tmp = []
for i in tmp2_ecoli:
    if i in map_features:
        tmp.append(map_features[i])

In [10]:
data['Site'] = tmp

In [11]:
data.head()

sequence_name   Mcg   Gvh   Lip  Chg   Aac  Alm1  Alm2  Site
0     AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35     0
1    ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44     0
2    ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46     0
3    ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36     0
4     ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35     0

In [12]:
data.to_json('tm.json',date_format='dd-mm-yy')
data.to_csv('tm.txt')
dataset = pd.read_csv('tm.txt',index_col=0)

dataset.drop(['sequence_name'],axis=1,inplace=True)
dataset.to_csv('finalecoli.txt')
class_ = dataset['Site']
dataset.drop(['Site'],axis=1,inplace=True)
dataset

Mcg   Gvh   Lip  Chg   Aac  Alm1  Alm2
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35
5    0.67  0.39  0.48  0.5  0.36  0.38  0.46
6    0.29  0.28  0.48  0.5  0.44  0.23  0.34
7    0.21  0.34  0.48  0.5  0.51  0.28  0.39
8    0.20  0.44  0.48  0.5  0.46  0.51  0.57
9    0.42  0.40  0.48  0.5  0.56  0.18  0.30
10   0.42  0.24  0.48  0.5  0.57  0.27  0.37
11   0.25  0.48  0.48  0.5  0.44  0.17  0.29
12   0.39  0.32  0.48  0.5  0.46  0.24  0.35
13   0.51  0.50  0.48  0.5  0.46  0.32  0.35
14   0.22  0.43  0.48  0.5  0.48  0.16  0.28
15   0.25  0.40  0.48  0.5  0.46  0.44  0.52
16   0.34  0.45  0.48  0.5  0.38  0.24  0.35
17   0.44  0.27  0.48  0.5  0.55  0.52  0.58
18   0.23  0.40  0.48  0.5  0.39  0.28  0.38
19   0.41  0.57  0.48  0.5  0.39  0.21  0.32
20   0.40  0.45  0.48  0.5  0.38  0.22  0.00
21   0.31  0.23  0.48  0.5  0.73  0.05  0.14
22   0.51  0.54  0.48  0.5  0.41  0.34  0.43
23   0.30  0.16  0.48  0.5  0.56  0.11  0.23
24   0.36  0.39  0.48  0.5  0.48  0.22  0.23
25   0.29  0.37  0.48  0.5  0.48  0.44  0.52
26   0.25  0.40  0.48  0.5  0.47  0.33  0.42
27   0.21  0.51  0.48  0.5  0.50  0.32  0.41
28   0.43  0.37  0.48  0.5  0.53  0.35  0.44
29   0.43  0.39  0.48  0.5  0.47  0.31  0.41
..    ...   ...   ...  ...   ...   ...   ...
306  0.63  0.71  0.48  0.5  0.60  0.40  0.39
307  0.71  0.86  0.48  0.5  0.40  0.54  0.32
308  0.68  0.78  0.48  0.5  0.43  0.44  0.42
309  0.64  0.84  0.48  0.5  0.37  0.45  0.40
310  0.74  0.47  0.48  0.5  0.50  0.57  0.42
311  0.75  0.84  0.48  0.5  0.35  0.52  0.33
312  0.63  0.65  0.48  0.5  0.39  0.44  0.35
313  0.69  0.67  0.48  0.5  0.30  0.39  0.24
314  0.70  0.71  0.48  0.5  0.42  0.84  0.85
315  0.69  0.80  0.48  0.5  0.46  0.57  0.26
316  0.64  0.66  0.48  0.5  0.41  0.39  0.20
317  0.63  0.80  0.48  0.5  0.46  0.31  0.29
318  0.66  0.71  0.48  0.5  0.41  0.50  0.35
319  0.69  0.59  0.48  0.5  0.46  0.44  0.52
320  0.68  0.67  0.48  0.5  0.49  0.40  0.34
321  0.64  0.78  0.48  0.5  0.50  0.36  0.38
322  0.62  0.78  0.48  0.5  0.47  0.49  0.54
323  0.76  0.73  0.48  0.5  0.44  0.39  0.39
324  0.64  0.81  0.48  0.5  0.37  0.39  0.44
325  0.29  0.39  0.48  0.5  0.52  0.40  0.48
326  0.62  0.83  0.48  0.5  0.46  0.36  0.40
327  0.56  0.54  0.48  0.5  0.43  0.37  0.30
328  0.69  0.66  0.48  0.5  0.41  0.50  0.25
329  0.69  0.65  0.48  0.5  0.63  0.48  0.41
330  0.43  0.59  0.48  0.5  0.52  0.49  0.56
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52

[336 rows x 7 columns]

In [13]:
dataset.shape

(336, 7)

In [14]:
features = dataset.as_matrix

In [15]:
features()

array([[ 0.49,  0.29,  0.48, ...,  0.56,  0.24,  0.35],
       [ 0.07,  0.4 ,  0.48, ...,  0.54,  0.35,  0.44],
       [ 0.56,  0.4 ,  0.48, ...,  0.49,  0.37,  0.46],
       ..., 
       [ 0.61,  0.6 ,  0.48, ...,  0.44,  0.39,  0.38],
       [ 0.59,  0.61,  0.48, ...,  0.42,  0.42,  0.37],
       [ 0.74,  0.74,  0.48, ...,  0.31,  0.53,  0.52]])

In [16]:
dataset

Mcg   Gvh   Lip  Chg   Aac  Alm1  Alm2
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35
5    0.67  0.39  0.48  0.5  0.36  0.38  0.46
6    0.29  0.28  0.48  0.5  0.44  0.23  0.34
7    0.21  0.34  0.48  0.5  0.51  0.28  0.39
8    0.20  0.44  0.48  0.5  0.46  0.51  0.57
9    0.42  0.40  0.48  0.5  0.56  0.18  0.30
10   0.42  0.24  0.48  0.5  0.57  0.27  0.37
11   0.25  0.48  0.48  0.5  0.44  0.17  0.29
12   0.39  0.32  0.48  0.5  0.46  0.24  0.35
13   0.51  0.50  0.48  0.5  0.46  0.32  0.35
14   0.22  0.43  0.48  0.5  0.48  0.16  0.28
15   0.25  0.40  0.48  0.5  0.46  0.44  0.52
16   0.34  0.45  0.48  0.5  0.38  0.24  0.35
17   0.44  0.27  0.48  0.5  0.55  0.52  0.58
18   0.23  0.40  0.48  0.5  0.39  0.28  0.38
19   0.41  0.57  0.48  0.5  0.39  0.21  0.32
20   0.40  0.45  0.48  0.5  0.38  0.22  0.00
21   0.31  0.23  0.48  0.5  0.73  0.05  0.14
22   0.51  0.54  0.48  0.5  0.41  0.34  0.43
23   0.30  0.16  0.48  0.5  0.56  0.11  0.23
24   0.36  0.39  0.48  0.5  0.48  0.22  0.23
25   0.29  0.37  0.48  0.5  0.48  0.44  0.52
26   0.25  0.40  0.48  0.5  0.47  0.33  0.42
27   0.21  0.51  0.48  0.5  0.50  0.32  0.41
28   0.43  0.37  0.48  0.5  0.53  0.35  0.44
29   0.43  0.39  0.48  0.5  0.47  0.31  0.41
..    ...   ...   ...  ...   ...   ...   ...
306  0.63  0.71  0.48  0.5  0.60  0.40  0.39
307  0.71  0.86  0.48  0.5  0.40  0.54  0.32
308  0.68  0.78  0.48  0.5  0.43  0.44  0.42
309  0.64  0.84  0.48  0.5  0.37  0.45  0.40
310  0.74  0.47  0.48  0.5  0.50  0.57  0.42
311  0.75  0.84  0.48  0.5  0.35  0.52  0.33
312  0.63  0.65  0.48  0.5  0.39  0.44  0.35
313  0.69  0.67  0.48  0.5  0.30  0.39  0.24
314  0.70  0.71  0.48  0.5  0.42  0.84  0.85
315  0.69  0.80  0.48  0.5  0.46  0.57  0.26
316  0.64  0.66  0.48  0.5  0.41  0.39  0.20
317  0.63  0.80  0.48  0.5  0.46  0.31  0.29
318  0.66  0.71  0.48  0.5  0.41  0.50  0.35
319  0.69  0.59  0.48  0.5  0.46  0.44  0.52
320  0.68  0.67  0.48  0.5  0.49  0.40  0.34
321  0.64  0.78  0.48  0.5  0.50  0.36  0.38
322  0.62  0.78  0.48  0.5  0.47  0.49  0.54
323  0.76  0.73  0.48  0.5  0.44  0.39  0.39
324  0.64  0.81  0.48  0.5  0.37  0.39  0.44
325  0.29  0.39  0.48  0.5  0.52  0.40  0.48
326  0.62  0.83  0.48  0.5  0.46  0.36  0.40
327  0.56  0.54  0.48  0.5  0.43  0.37  0.30
328  0.69  0.66  0.48  0.5  0.41  0.50  0.25
329  0.69  0.65  0.48  0.5  0.63  0.48  0.41
330  0.43  0.59  0.48  0.5  0.52  0.49  0.56
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52

[336 rows x 7 columns]

In [17]:
class_

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
306    4
307    4
308    4
309    4
310    4
311    4
312    4
313    4
314    4
315    4
316    4
317    4
318    4
319    4
320    4
321    4
322    4
323    4
324    4
325    4
326    4
327    4
328    4
329    4
330    4
331    4
332    4
333    4
334    4
335    4
Name: Site, dtype: int64

In [18]:
def euclidian(a, b):
    return np.linalg.norm(a-b)

In [57]:
def kmeans(k,dataset, epsilon=0, distance='euclidian'):
    print("Working...")
    history_centroids = []
    if distance == 'euclidian':
        dist_method = euclidian
    # dataset = dataset[:, 0:dataset.shape[1] - 1]
    num_instances, num_features = dataset.shape
    prototypes = dataset[np.random.randint(0, num_instances - 1, size=k)]
    history_centroids.append(prototypes)
    prototypes_old = np.zeros(prototypes.shape)
    belongs_to = np.zeros((num_instances, 1))
    norm = dist_method(prototypes, prototypes_old)
    iteration = 0
    while norm > epsilon:
        iteration += 1
        norm = dist_method(prototypes, prototypes_old)
        prototypes_old = prototypes
        for index_instance, instance in enumerate(dataset):
            dist_vec = np.zeros((k, 1))
            for index_prototype, prototype in enumerate(prototypes):
                dist_vec[index_prototype] = dist_method(prototype,instance)
            belongs_to[index_instance, 0] = np.argmin(dist_vec)
        tmp_prototypes = np.zeros((k, num_features))
        for index in range(len(prototypes)):
            instances_close = [i for i in range(len(belongs_to)) if belongs_to[i] == index]
            prototype = np.mean(dataset[instances_close], axis=0)
            # prototype = dataset[np.random.randint(0, num_instances, size=1)[0]]
            tmp_prototypes[index, :] = prototype

        prototypes = tmp_prototypes

        history_centroids.append(tmp_prototypes)

    # plot(dataset, history_centroids, belongs_to)
    print(prototypes)
    print("DONE!")
    return prototypes, history_centroids, belongs_to

In [67]:
k=8
centroids, history_centroids, belongs_to = kmeans(k,features())


Working...
[[ 0.67257143  0.78114286  0.48        0.5         0.41457143  0.45314286
   0.346     ]
 [ 0.28893939  0.43166667  0.48        0.5         0.45378788  0.40090909
   0.46272727]
 [ 0.58478261  0.5273913   0.5026087   0.5         0.56326087  0.76413043
   0.78173913]
 [ 0.64393939  0.53030303  0.57454545  0.51515152  0.44060606  0.50939394
   0.34939394]
 [ 0.671       0.6955      0.506       0.5         0.7465      0.4635
   0.3145    ]
 [ 0.3         0.4796      0.48        0.5         0.5552      0.7732      0.77      ]
 [ 0.39051948  0.38727273  0.48        0.5         0.45519481  0.24922078
   0.33922078]
 [ 0.77264706  0.43205882  0.49529412  0.5         0.56588235  0.76441176
   0.76794118]]
DONE!


In [68]:
for index,centroid in enumerate(centroids):
    print("#{} C({})".format(index,centroid))

#0 C([ 0.67257143  0.78114286  0.48        0.5         0.41457143  0.45314286
  0.346     ])
#1 C([ 0.28893939  0.43166667  0.48        0.5         0.45378788  0.40090909
  0.46272727])
#2 C([ 0.58478261  0.5273913   0.5026087   0.5         0.56326087  0.76413043
  0.78173913])
#3 C([ 0.64393939  0.53030303  0.57454545  0.51515152  0.44060606  0.50939394
  0.34939394])
#4 C([ 0.671   0.6955  0.506   0.5     0.7465  0.4635  0.3145])
#5 C([ 0.3     0.4796  0.48    0.5     0.5552  0.7732  0.77  ])
#6 C([ 0.39051948  0.38727273  0.48        0.5         0.45519481  0.24922078
  0.33922078])
#7 C([ 0.77264706  0.43205882  0.49529412  0.5         0.56588235  0.76441176
  0.76794118])


In [69]:
def predict(centroids,vector_test):
    tmp_dist = 9999
    dist_vec = np.zeros((k,1))
    for index_centroid,centroid in enumerate(centroids):
        if euclidian(centroid,vector_test) <= tmp_dist:
            tmp_dist = euclidian(centroid,vector_test)
            closest_centroid = centroid
    return np.argmin(np.sum((centroids - vector_test)**2, axis=1)),closest_centroid

In [70]:
trying = [0.31,0.36,0.48,0.5,0.58,0.94,0.94]

In [71]:
belong_to,closest_centroid=predict(centroids,trying)

In [72]:
belong_to,closest_centroid

(5, array([ 0.3   ,  0.4796,  0.48  ,  0.5   ,  0.5552,  0.7732,  0.77  ]))

In [73]:
map_features

{'cp': 0, 'im': 7, 'imL': 2, 'imS': 1, 'imU': 5, 'om': 6, 'omL': 3, 'pp': 4}

In [74]:
belongs_to

array([[ 6.],
       [ 1.],
       [ 6.],
       [ 3.],
       [ 6.],
       [ 3.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 3.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 3.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 3.],
       [ 1.],
       [ 1.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 6.],
       [ 1.],
       [ 6.],
       [ 6.],
       [ 1.],
       [ 1.],
       [ 3.],
       [ 6.],
       [ 1.],
       [ 6.],
      

In [66]:
features()

array([[ 0.49,  0.29,  0.48, ...,  0.56,  0.24,  0.35],
       [ 0.07,  0.4 ,  0.48, ...,  0.54,  0.35,  0.44],
       [ 0.56,  0.4 ,  0.48, ...,  0.49,  0.37,  0.46],
       ..., 
       [ 0.61,  0.6 ,  0.48, ...,  0.44,  0.39,  0.38],
       [ 0.59,  0.61,  0.48, ...,  0.42,  0.42,  0.37],
       [ 0.74,  0.74,  0.48, ...,  0.31,  0.53,  0.52]])